Add xterm and hostname fix for RealVNC server
RealVNC server fails to start if it is unable to resolve it's hostname when launched without a session.

This was temporarily fixed by adding an entry to /etc/hosts, but would not update without a re-deploy.  This has since been disabled in preference of launching without a force hostname lookup for `vncserver`

Without a proper hostname, one may see something like this:

```
$ vncserver
VNC(R) Server 5.2.3 (r8648) 64-bit (Jan 28 2015 15:47:49)
Copyright (C) 2002-2015 RealVNC Ltd.
VNC is a registered trademark of RealVNC Ltd in the U.S. and in other
countries.
Protected by UK patent 2481870; US patent 8760366.
See http://www.realvnc.com for information on VNC.
For third party acknowledgements see:
http://www.realvnc.com/products/vnc/documentation/5.2/acknowledgements.txt

xauth: (argv):1:  bad display name "vmXX-YYY.iplantcollaborative.org:1" in "add" command
Error: could not run xauth
```

By simply providing a session to start under, this prevents hostname resolution.

More information here: <https://support.realvnc.com/Knowledgebase/Article/View/231/1/error-could-not-run-xauth>

	modified:   playbooks/21_atmo_hostname.yml
	modified:   roles/atmo-realvncserver/tasks/main.yml
	modified:   roles/atmo-realvncserver/vars/CentOS.yml